#!/bin/sh

global.linux.bootargs.dyn.root="ro rootdelay=3"

if [ -f /mnt/mmc1.1/boot/Image.gz ]; then
	echo "Booting from SD"

	DTB=/mnt/mmc1.1/boot/imx8mm-diasom-som-evb.dtb

	global.bootm.root_dev=mmc1.1
	global.bootm.image=/mnt/mmc1.1/boot/Image.gz
elif [ -f /mnt/mmc0.1/boot/Image.gz ]; then
	echo "Booting from eMMC"

	DTB=/mnt/mmc0.1/boot/imx8mm-diasom-som-evb.dtb

	global.bootm.root_dev=mmc0.1
	global.bootm.image=/mnt/mmc0.1/boot/Image.gz
else
	echo "Boot image not found!"
	exit 1
fi

if [ -f $DTB ]; then
	echo "Using external devicetree blob from $DTB"
	global.bootm.oftree=$DTB
else
	echo "Using internal devicetree blob"
fi

exit 0
