#!/bin/sh

# Enable framebuffer on HDMI output
if [ -e /dev/fb0 ]; then
	fb0.enable=1

	LOGO=/mnt/mmc0.2/usr/local/share/weston/diasom.png
	[ -f $LOGO ] || DTBODIR=/mnt/mmc1.2/usr/local/share/weston/diasom.png

	# Show DIASOM logo
	[ -f $LOGO ] && splash -f /dev/fb0 $LOGO
fi

exit 0
